### ISSUE TITLE
Cast Exception MetadataUserDetails

### ISSUE THREAD

**Issue by gjeanmart** [nico-arianto/jasperserver-war-keycloak#2]
Hi,

First of all, thank you for sharing this!

I've successfully integrated your code into my _Jasperserver-pro 6.3_ with _Keycloak 2.0.0_, the authentication through Keycloak works well but I got the following exception when I try to run a report into the admin console.

> com.jaspersoft.jasperserver.api.security.externalAuth.keycloak.KeycloakUserDetails cannot be cast to com.jaspersoft.jasperserver.api.metadata.user.domain.impl.client.MetadataUserDetails

![image](https://cloud.githubusercontent.com/assets/506784/24367758/c358b662-1315-11e7-95d7-8f6130673f8c.png)

It seems that Jasper expects a session object inherited from **MetadataUserDetails** but KeycloakUserDetails is inherited from KeycloakPrincipal.

Have you faced the same issue ?

Thank you.

**Comment by nico-arianto** [comment]
Hi,

It didn't happen to me before, but AFAIK in one of Jasper filter (or handler) did override the KeycloackUserDetails to MetadataUserDetails and I skipped this behavior.

Try check in JrsExternalKeycloakAuthenticationSuccessHandler classes.

One more important note, if you're not using Single Sign Out, we can let Jasper override the credential to MetadataUserDetails and everything should work as normal.

Do note that if we are going to use MetadataUserDetails, Keylock Single Sign Out will not works.

For more details about the Single Sign Out, you can view the code in org.keycloak.adapters.springsecurity.authentication.KeycloakLogoutHandler.

**Comment by gjeanmart** [comment]
Hi,
Thank you for your answer, I actually tried to find any reference of **MetadataUserDetails** and I only found one in _KeycloakUserSetupProcessor.updateAuthentication(User user)_

`final MetadataUserDetails userDetails = new MetadataUserDetails(user);`

But I don't think this affect the authentication process. 

When you say _"I skipped this behavior."_, How did you do that ? is it part of the code or any other configuration ?

I'm actually using exactly the same code as you except I package it as a JAR file and copied it + each Keycloak dependency in _WEB-INF/lib_ folder.

Thank you for your help.

**Comment by gjeanmart** [comment]
I found what you meant about _'skipped this behavior'_. The bean **UserProfileBuiltInParameterProvider** is used to automatically inject user attributes as a parameter in the report if the attribute name matches with the report paramater. This bean ties to cast the KeycloakPrincipal into MetadataUserDetails in order to call _getAttributes()_ . But it doesn't work because KeycloakUserDetails doesn't inherit from MetadataUserDetails.

As you explained, this feature can be skipped if not needed (that my case) by getting rid of 
```
<bean class="com.jaspersoft.jasperserver.api.engine.jasperreports.util.UserProfileBuiltInParameterProvider">
    <property name="profileAttributeService" ref="profileAttributeService"/>
    <property name="profileAttributeCategories" ref="${bean.profileAttributeCategories}"/>
</bean>
```

in **WEB-INF\applicationContext.xml**

Thank again for your help.
